name: nn-env

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython
  - matplotlib
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pip
  - pip:
    - jupyter-book==0.11.3
    - tqdm
    - ipt