name: ml-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9  # Change this to desired Python version
  - ipython
  - notebook
  - matplotlib
  - pandas
  - scikit-learn
  - numpy
  - scipy
  - seaborn
  - statsmodels
  - jupyterlab
  - nodejs
  - xeus-python
  - black
  - flake8
  - pytest