name: your_module_name
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - cudatoolkit
  - ipython
  - notebook
  - matplotlib
  - pandas
  - scikit-learn
  - numpy
  - scipy
  - seaborn
  - statsmodels
  - jupyterlab
  - nodejs
  - xeus-python
  - black
  - flake8
  - pytest
  - pip
  - pip:
    - jax
    - jaxlib
    - optax
    - tqdm